name: beneficios_ao_cidadao
version: "1.0.0"
config-version: 2

profile: beneficios

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  beneficios_ao_cidadao:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
